title: Matiboux.me
description: The home page and the central point of me.
author: Matiboux
logo: https://avatars0.githubusercontent.com/u/7428799?s=300
stylesheets:
- https://use.fontawesome.com/releases/v5.6.3/css/all.css
- https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css
